global:
  domain: argocd.devsecopsdeployed.com

server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "argocd.devsecopsdeployed.com"
    tls: false
    extraTls:
    - hosts:
      - argocd.devsecopsdeployed.com
      secretName: argocd-tls
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS


